export const InvalidEmail = [
    ,"      @mail.com"
    ,"abc   @mail.com"
    ,"@mail.com"
    ,"abc@      "
    ,"abc@"
    ,"abc.com"
    ,"abc..def@mail.com"
    ,".abc@mail.com"
    ,"abc.def@mail#archive.com"
    ,"abc.def@mail"
    ,"abc.def@mail..com"
];
export const ValidEmail = [
    "433333132314abc@mail.cc"
    // ,"1abc-d@mail.com"
    // ,"1abc.def@mail.com"
    // ,"1abc_def@mail.com"
    // ,"1abc.def@mail-archive.com"
    // ,"   abc@gmail.com1"
]
export const InvalidPassword = [
    ""
    ,"      @mail.com"
    ,"abc   @mail.com"
    ,"@mail.com"
    ,"abc@      "
    ,"abc@"
    ,"abc.com"
    ,"abc..def@mail.com"
    ,".abc@mail.com"
    ,"abc.def@mail#archive.com"
    ,"abc.def@mail"
    ,"abc.def@mail..com"
]